version: 2
jobs:
    lint-and-test-job:
        working_directory: ~/project
        docker:
            - {image: 'circleci/node:8.8.1-browsers'}
        steps:
            - checkout
            - {run: {name: 'Show current branch', command: 'echo ${CIRCLE_BRANCH}'}}
            - {restore_cache: {keys: ['v1-dependencies-{{ checksum "package.json" }}', v1-dependencies-]}}
            - {run: {name: 'Install local dependencies', command: 'npm install'}}
            - {save_cache: {key: 'v1-dependencies-{{ checksum "package.json" }}', paths: [node_modules]}}
            - {run: {name: Linting, command: 'npm run lint'}}
            - {run: {name: Testing, command: 'npm run test'}}
    deploy-job:
        steps:
            - checkout
            - {run: null, name: 'Deploy Master to Heroku', command: 'git push https://heroku:0d943091-412d-4846-bbfa-da57d47f08c3@git.heroku.com/lets-job.git master'}
workflows:
    version: 2
    
    deploy:
        jobs:
            - lint-and-test-job
            - {deploy-job: {requires: [lint-and-test-job], filters: {branches: null, only: master}}}
